# Site settings
title: craftxbox
description: "Programs and other content."
baseurl: ""
url: "https://craftxbox.com"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
